enum TppEventGroup {
    Logging
    VenafiConfiguration
    VenafiSecretStore
    VenafiCredentials
    VenafiPermissions
    Vagent
    VenafiDiscovery
    Identity
    VenafiCertificateManager
    VenafiWorkflow
    VenafiCertificateCore
    AdminUI
    VenafiCertificateAuthority
    VenafiPlatform
    VenafiSSHWorkflow
    VenafiEncryption
    VenafiMonitoring
    VenafiValidationService
    VenafiCredentialMonitoring
    LogClient
    VenafiReporter
    VenafiMonitor
    NetworkDeviceEnrollment
    Aperture
    CertificateRevocation
    SSHManagerServiceModule
    VenafiCAImport
    SSHManagerClientRestModule
    UserPortal
    CertificateReports
    ClientRestService
    VenafiTrustNetIntegration
    VenafiOnboardDiscovery
    WebSDKRESTAPI
    VenafiCloudInstanceMonitoring
    ACMEService
    VenafiSoftwareEncryption
    VenafiHardwareEncryption
    IdentityAD
    IdentityLocal
    IdentityLDAP
    LogMsSql
    LogSplunk
    LogAdaptable
    MicrosoftCA
    SymantecMPKI
    RedhatCA
    EntrustDotNet
    UniCERT
    Thawte
    RSA
    GeoTrustCA
    DigiCertCA
    OpenSSLCA
    GlobalSignMSSLCA
    GeoTrustEnterpriseCA
    OpenTrustPKICA
    SelfsignedCA
    TrustwaveCA
    QuoVadisCA
    HydrantIdCA
    ComodoCCMCA
    GeoTrustTrueFlexCA
    Xolphin
    AmazonCA
    Adaptable
    Apache
    GlobalSecurityKit
    IIS6
    X509Certificate
    VenafiSSH
    VenafiHTTP
    VenafiSQL
    Pkcs12
    Application
    IIS5
    CiscoACE
    CiscoCSS
    JavaKeystore
    iPlanet
    NetScaler
    VAMnShield
    DataPower
    TealeafPCA
    PEM
    F5LTMAdvanced
    Basic
    ImpervaMX
    A10AXTM
    Layer7SSG
    JuniperSAS
    ConnectDirect
    BlueCoat
    PaloAlto
    AmazonApp
    AzureKeyVault
    Common
    RiverbedSteelHead
    AdaptableApp
    CAPI
    AgentKeystore
    AgentSsh
    Migration
    AWSEC2CloudInstanceMonitoringDriver
    CyberArk
    VenafiTools
    Tracing
}
